### ISSUE TITLE
Contact page h4

### ISSUE THREAD

**Issue by MysticalMike60t** [MysticalMike60t/itdepartment#7]
h4 tags have a grey background.
Fix:
```css
@media screen and (max-width: width when changed to a button) {
  h4 {
    background: rgb(35,35,35);
  }
}
```
